name: release

on:
  push:
    tags:
      - 'v**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install wheel
        run: pip install wheel
      
      - name: Build dist
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        run: |
          pip install twine
          twine upload dist/* --skip-existing -p ${{ secrets.PYPI_API_TOKEN }}
